#!/bin/sh

# variables
VOSK_MODEL_PATH_EN="$HOME/.local/share/music_fairy/vosk-model-small-en-in-0.4/"
INVIDIOUS_INSTANCE="https://vid.puffyan.us" # some instances might not work

VOSK_MODEL_PATH_HI="$HOME/.local/share/music_fairy/vosk-model-small-hi-0.22/"
#INVIDIOUS_INSTANCE="https://vid.puffyan.us" # some instances might not work
# stop current song, clear playlist
mpc stop
mpc clear

# take mic input
ffmpeg -y -f alsa -i default -acodec pcm_s16le -ac 1 -ar 44100 -t 4 -f wav ~/.cache/audio.wav

# convert it into text & store it in `audio_input`
vosk-transcriber -m $VOSK_MODEL_PATH_EN -i ~/.cache/audio.wav -o ~/.cache/audio_text.txt
read audio_input_en < ~/.cache/audio_text.txt


vosk-transcriber -m $VOSK_MODEL_PATH_HI -i ~/.cache/audio.wav -o ~/.cache/audio_text.txt
read audio_input_hi < ~/.cache/audio_text.txt

google_speech " Please choose the Language.."
options=("1) HI-$audio_input_hi" , "2) EN-$audio_input_en")
select opt in "${options[@]}"
do
	case $opt in
		"1) HI-$audio_input_hi"
			audio_input=audio_input_hi
			break
			;;

		"2) EN-$audio_input_en"
			audio_input=audio_input_en
			break
			;;
		*) echo "Invalid option $REPLY";;
	esac
done


# Audio confirmation notification
google_speech " All right.. let me play.. $audio_input" &

# make youtube search query
query="$(printf '%s' "song audio $audio_input" | tr ' ' '+' )"

# search on invidous (youtube) instance for video id to make a url
video_id="$(curl -s "$INVIDIOUS_INSTANCE/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
youtube_url="https://youtube.com/$video_id"

# get url for bestaudio stream from the youtube video
audio_url="$(yt-dlp -f bestaudio --get-url "$youtube_url")"

# add the track to mpd and play
mpc add "$audio_url"
mpc play
mpc play
# Get youtube video title for system notification
title=$(yt-dlp --get-title "$youtube_url")
notify-send "Playing: " "$title"
